/**
 * Centralized configuration for contract addresses
 * Auto-generated by deployment scripts
 */

const fs = require('fs');
const path = require('path');

// Load latest deployment
const deploymentPath = path.join(__dirname, 'deployments/sepolia-latest.json');

let deployment = null;

if (fs.existsSync(deploymentPath)) {
  deployment = require('./deployments/sepolia-latest.json');
}

module.exports = {
  network: deployment?.network || 'sepolia',
  chainId: deployment?.chainId || 11155111,
  
  contracts: {
    userRegistry: deployment?.contracts.UserRegistry.address || null,
    campaignFactory: deployment?.contracts.CampaignFactory.address || null
  },
  
  // ABIs (can be loaded from Foundry output)
  abis: {
    userRegistry: require('../contracts/out/UserRegistry.sol/UserRegistry.json').abi,
    campaignFactory: require('../contracts/out/CampaignFactory.sol/CampaignFactory.json').abi
  },
  
  // Helper function
  getContractAddress: (name) => {
    const addresses = {
      'UserRegistry': deployment?.contracts.UserRegistry.address,
      'CampaignFactory': deployment?.contracts.CampaignFactory.address
    };
    return addresses[name] || null;
  }
};